id: ...
container:
  type: DOCKER
  docker:
    image: ...
    forcePullImage: true
    network: HOST
instances: 1
cpus: ...
mem: 8...
uris: []
env:
  SERVICE_TAGS: babl
  BABL_MODULE: ...
  BABL_COMMAND: /bin/app
cmd: ...
