id: ...
container:
  type: DOCKER
  docker:
    image: ...
    forcePullImage: false
    network: BRIDGE
    portMappings:
      - hostPort: 0
    parameters:
      -
        key: log-driver
        value: gelf
      -
        key: log-opt
        value: gelf-address=udp://babl-satellite1:4988
      -
        key: log-opt
        value: env=BABL_MODULE,BABL_MODULE_VERSION,SERVICE_TAGS
instances: 1
cpus: 0.1
mem: 16
uris: []
env:
  SERVICE_TAGS: babl
  BABL_MODULE: ...
  BABL_COMMAND: /bin/app
  BABL_KAFKA_BROKERS: queue.babl.sh:9092
cmd: babl-server
